### ISSUE TITLE
Deploy the main branch to a server

### ISSUE THREAD

**Issue by salehpirouzi-cyf** [khmdagal/The-Collective-Foundation#11]
User Story

AS A user (both external and admin) 
I WANT TO to reach the Collective Foundation website
SO THAT I can make view information about Collective Foundation

Acceptance Criteria

GIVEN I am on the Collective Foundation website
WHEN I view the home page
THEN it should display the latest version of the website

**Comment by salehpirouzi-cyf** [comment]
0.5

**Comment by JihadOmer** [comment]
The website is running and it is reachable on the like

**Comment by KhesiweDube** [comment]
I am able to access this URL and can see Hello message and  About link is accesible. I am moving this ticket to Done
