### ISSUE TITLE
Create the most basic version of the project

### ISSUE THREAD

**Issue by salehpirouzi-cyf** [khmdagal/The-Collective-Foundation#12]
User Story

AS A user (both external and admin)
I WANT TO to reach the Collective Foundation website
SO THAT I can view admin pages and what admin has created

Acceptance Criteria

GIVEN I am on Collective Foundation website
WHEN I view the admin page
THEN it should display the information of two pages with different modules

GIVEN I am on Collective Foundation website
WHEN I view the admin page
THEN it should display the not-implemented version of the 'Add Module' feature

GIVEN I am on Collective Foundation website
WHEN I view the admin page
THEN it should display the not-implemented version of the 'Add Page' feature

GIVEN I am on Collective Foundation website
WHEN I view the page1
THEN it should display the basic version of the modules stated in admin page for page 1

GIVEN I am on Collective Foundation website
WHEN I view the page2
THEN it should display the basic version of the modules stated in admin page for page 2

**Comment by salehpirouzi-cyf** [comment]
2

**Comment by khmdagal** [comment]
ready for review
