### ISSUE TITLE
[UI] Navigation between pages - Footer

### ISSUE THREAD

**Issue by salehpirouzi-cyf** [khmdagal/The-Collective-Foundation#13]
User Story

AS A user who has reached the Collective Foundation website
I WANT TO be able navigate
SO THAT I can view all of the pages in the website

Acceptance Criteria

GIVEN I am on the main website/homepage page
WHEN I view the bottom of the page
THEN I would see the footer (Address on the left, pages in the right, social icons on the right)

GIVEN I am on the main website/homepage page
WHEN I click a linked paged in the footer
THEN it takes me to the page I have clicked

**Comment by salehpirouzi-cyf** [comment]
3

**Comment by salehpirouzi-cyf** [comment]
![Image](https://user-images.githubusercontent.com/102039379/223477432-54fb6d47-0ba4-46b1-80f1-50ac115277f3.png)

Social icons can be simple links to the the social website (like http://www.facebook.com/)

DO NOT REIMPLEMENT THE API WHICH RETURNS ALL PAGES. USE THE SAME API AS THE ONE IMPLEMENTED IN [THIS TICKET](https://github.com/users/khmdagal/projects/6/views/1?pane=issue&itemId=22061575)

**Comment by George-Cleal** [comment]
Blocked by https://github.com/users/khmdagal/projects/6/views/1?pane=issue&itemId=22061575

**Comment by KhesiweDube** [comment]
I have raised a defect for this user story see attachement :[https://khesiwe.atlassian.net/browse/CFW-1](url)

**Comment by Doris-Siu** [comment]
Finished review.
