### ISSUE TITLE
[UI] Text Banner Module

### ISSUE THREAD

**Issue by salehpirouzi-cyf** [khmdagal/The-Collective-Foundation#21]
This ticket is for having a Text Banner module which is like this image:

![Image](https://user-images.githubusercontent.com/102039379/224472400-a69d5d75-4aee-431d-86c8-1811d7b6d978.png)

There should be an option for this component to select the background colour.
You can assume the text on the left is always bold, and the right is always normal.

**This is issue is simply for the frontend component, but component has to work with props so that it can be rendered multiple times**

**Comment by KhesiweDube** [comment]
@Doris-Siu I aam not able to see this picture implemented on the current application

![Image](https://user-images.githubusercontent.com/101154626/226359391-facf045f-488a-4232-bad9-bdc4b6061150.png)

**Comment by KhesiweDube** [comment]
@Shimaadnan @khmdagal @JihadOmer 

Could you please look at this ticket please

**Comment by Shimaadnan** [comment]
I can not see the text in the box. @JihadOmer can you please check as well

**Comment by KhesiweDube** [comment]
@JihadOmer i have raised a defect for this feature:
https://khesiwe.atlassian.net/browse/CFW-5

**Comment by JihadOmer** [comment]
@KhesiweDube if I am not wrong, I think the position for a module depends on the order it has been added to the page.

**Comment by KhesiweDube** [comment]
Ok i have gotten clarification from saleh that the  text banner can be anyway. so i am moving this ticket to Done
