### ISSUE TITLE
create pre-defined Text&Image and add it to Home and Contact page

### ISSUE THREAD

**Issue by salehpirouzi-cyf** [khmdagal/The-Collective-Foundation#24]
At the end of this ticket, We should be able to see the content for two separate Text&Image modules (one for Home page and one for Contact page)

Required fields for this module are determined by issue #14

**Comment by salehpirouzi-cyf** [comment]
![Image](https://user-images.githubusercontent.com/102039379/224492891-adb69c62-799f-40aa-b58f-1075615c2868.png)



![Image](https://user-images.githubusercontent.com/102039379/224492902-5eeba828-41ff-45b4-8ae2-6e83bab23f61.png)

**Comment by George-Cleal** [comment]
@salehpirouzi-cyf to review and suggest improvements. This will count as one of the 2 required reviews
