### ISSUE TITLE
Navigation and links between pages

### ISSUE THREAD

**Issue by George-Cleal** [khmdagal/The-Collective-Foundation#38]
User Story:

AS A non-admin user on the website
I WANT TO click to navigate between page
SO THAT I can navigate and view multiple pages

Note - suggested we use the simplest possible solution (e.g. hyperlink) in the interest of speed.

These should use database links rather than static links

**Comment by KhesiweDube** [comment]
@JihadOmer i still see the hyperlinks of the header and the footer are not working , actual when i clink on those links it is not taking me to the respective pages, also the alignment pf footer links are not at proper places


![Image](https://user-images.githubusercontent.com/101154626/227614829-ff990861-dd2c-4cf6-afd8-a49368aad50a.png)
