### ISSUE TITLE
Make content on 2nd page different

### ISSUE THREAD

**Issue by George-Cleal** [khmdagal/The-Collective-Foundation#40]
USER STORY

AS A non-admin user on the website
I WANT TO  see different content on the 2nd page
SO THAT I get more information from clicking onto it

Note - dummy/placeholder image & text content is fine for now, it just needs to be different from the 1st page

**Comment by George-Cleal** [comment]
Likely this can be covered in https://github.com/khmdagal/The-Collective-Foundation/issues/5, so can be closed once #5 is complete

**Comment by KhesiweDube** [comment]
User is able to access the 2nd page of the application and can see the images and text which is defferent from the first page
