### ISSUE TITLE
Add & define content modules to an existing page in admin panel

### ISSUE THREAD

**Issue by George-Cleal** [khmdagal/The-Collective-Foundation#5]
**User Story:**

AS AN admin
I WANT TO add and define content modules to an existing page
SO THAT I can add my website content

**Acceptance Criteria:**

GIVEN I am an admin 
WHEN I click to add a content module to an existing page e.g. Home
THEN I want to see a basic form appear to "add content" (text, image, button)

GIVEN I am an admin who is viewing the "add content form"
WHEN I have filled in some content 
THEN I can click 'Save" to publish that new module and its content to the website

GIVEN I am an admin who is viewing the "add content form"
WHEN I click "close"/X
THEN the form closes and I return to the admin page without adding a module

GIVEN I am an admin who is viewing the "add content form"
WHEN I haven't entered any data yet
THEN I am unable to add the module until it has at least some content e.g. one character/image

GIVEN I have just created a content module for an existing page
WHEN I refresh and view the page for which I have created the module 
THEN I see the new content module on that page

GIVEN I am an admin who has just added a module
WHEN I refresh the admin page
THEN I see an updated list of existing all content modules (showing which page they're on), including the one I have just created

- All modules must be within an existing page
- There is a backlog feature which we may build if time to preview the website/modules when building it but not included in this ticket

**Comment by George-Cleal** [comment]
Step 1: admin selects page to add a module to and chooses to add it
Step 2: form shows to define content (image and/or text)
Step 3: admin completes and select "Create module"
Step 4: admin page and web page updates

**Comment by George-Cleal** [comment]
Blocks https://github.com/khmdagal/The-Collective-Foundation/issues/7

**Comment by KhesiweDube** [comment]
On about page , When i add a hero banner module, the image and the text does not align with the application pa

**Comment by khmdagal** [comment]
I think it is realated to CSS style rules about the elements in the herobanner componnet?
