### ISSUE TITLE
Delete a content module

### ISSUE THREAD

**Issue by George-Cleal** [khmdagal/The-Collective-Foundation#7]
**User Story**

AS AN admin
I WANT TO delete a module
SO THAT I can remove modules from my website

**Acceptance Criteria**

GIVEN I am a password authenticated admin on the admin portal
WHEN I click to delete a module
THEN a warning dialogue shows "Are you sure you want to delete this module and all of its content?" Options "Yes" & "No"

GIVEN I am viewing the warning dialogue
WHEN I click "Yes" // "No"
THEN the module and all of its content is deleted // I am returned to the admin portal and the module is not deleted

**Comment by George-Cleal** [comment]
Delete module will be deleted from database (and therefore from admin page and the relevant web page when refreshed)

**Comment by George-Cleal** [comment]
Blocked by https://github.com/khmdagal/The-Collective-Foundation/issues/5

**Comment by KhesiweDube** [comment]
I have retested and raised a defect 
https://khesiwe.atlassian.net/jira/software/projects/CFW/boards/1?selectedIssue=CFW-3

**Comment by KhesiweDube** [comment]
I have retested and raised a defect

**Comment by KhesiweDube** [comment]
Im closiing this ticket , evrything is working as expected
