### ISSUE TITLE
[UI] Navigation between pages - Header

### ISSUE THREAD

**Issue by George-Cleal** [khmdagal/The-Collective-Foundation#9]
**User Story**

AS A user who has reached the Collective Foundation website
I WANT TO be able navigate 
SO THAT I can view all of the pages in the website

**Acceptance Criteria**

GIVEN I am on the main website/homepage page
WHEN I view the top of the page
THEN I would see the header (logo on the left, pages in the right, social icons on the right)

GIVEN I am on the main website/homepage page
WHEN I click a linked page
THEN it takes me to the page I have clicked

**Comment by salehpirouzi-cyf** [comment]
3

**Comment by salehpirouzi-cyf** [comment]
![Image](https://user-images.githubusercontent.com/102039379/223474691-5b3bc35d-7f47-420d-b311-71a06d51f33f.png)



![Image](https://user-images.githubusercontent.com/102039379/223474819-591caf09-3f0d-425b-bd80-3a783f8647d2.png)


Social icons can be simple links to the the social website (like http://www.facebook.com)


**DO NOT REIMPLEMENT THE API WHICH RETURNS ALL PAGES. USE THE SAME API AS THE ONE IMPLEMENTED IN [THIS TICKET](https://github.com/users/khmdagal/projects/6/views/1?pane=issue&itemId=22061575)**

**Comment by George-Cleal** [comment]
Blocked by: https://github.com/users/khmdagal/projects/6/views/1?pane=issue&itemId=22061575

**Comment by Doris-Siu** [comment]
@KhesiweDube position issue is fixed, no navigation for now as team agreed not to move any DB here

![Image](https://user-images.githubusercontent.com/107772913/225785426-11f47d1d-cfa8-42ca-aed5-1eca62f9d903.png)

**Comment by KhesiweDube** [comment]
Moving to closed because this ticket is now combined and covered in: #38
